pipeline:
  identifier: Build_simple_java_maven_app_1729675533327
  name: Build simple-java-maven-app
  orgIdentifier: default
  projectIdentifier: CI_Testing
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.andydpage
        repoName: simple-java-maven-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Build
                  spec:
                    connectorRef: account.andydpage_dockerhub
                    image: maven:3.8.7
                    shell: Sh
                    command: |-
                      mvn -B -DskipTests clean package
                      echo "Build complete...."
                  timeout: ""
                  type: Run
              - step:
                  type: Test
                  name: Unit Tests
                  identifier: Unit_Tests
                  spec:
                    connectorRef: account.andydpage_dockerhub
                    image: maven:3.8.7
                    shell: Sh
                    command: |-
                      mvn -B -DskipTests clean package
                      mvn test
                    intelligenceMode: true
              - step:
                  type: RunTests
                  name: Unit Test 2
                  identifier: Unit_Test_2
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
